import { useState, useEffect, useCallback, useRef } from "react";
import { chatApi } from "../api/chatApi.js";

const useDebounce = (value, delay = 350) => {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => {
    const t = setTimeout(() => setDebounced(value), delay);
    return () => clearTimeout(t);
  }, [value, delay]);
  return debounced;
};

const useChatHistory = () => {
  const [chats,        setChats]        = useState([]);
  const [isLoading,    setIsLoading]    = useState(true);
  const [isSearching,  setIsSearching]  = useState(false);
  const [searchQuery,  setSearchQuery]  = useState("");
  const [error,        setError]        = useState(null);
  const [pagination,   setPagination]   = useState({ page: 1, totalPages: 1, total: 0 });
  const [activeStatus, setActiveStatus] = useState("active");

  const debouncedQuery = useDebounce(searchQuery, 350);
  const abortRef = useRef(null);

  const fetchChats = useCallback(async (page = 1, status = activeStatus) => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await chatApi.list({ page, limit: 20, status });
      setChats(data.chats);
      setPagination(data.pagination);
    } catch (err) {
      setError(err.userMessage || "Failed to load chat history.");
    } finally {
      setIsLoading(false);
    }
  }, [activeStatus]);

  useEffect(() => {
    fetchChats(1, activeStatus);
  }, [activeStatus, fetchChats]);

  useEffect(() => {
    if (!debouncedQuery.trim()) {
      fetchChats(1, activeStatus);
      return;
    }

    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    const runSearch = async () => {
      setIsSearching(true);
      setError(null);
      try {
        const data = await chatApi.search(debouncedQuery);
        if (!controller.signal.aborted) {
          setChats(data.chats);
          setPagination({ page: 1, totalPages: 1, total: data.chats.length });
        }
      } catch (err) {
        if (!controller.signal.aborted) setError(err.userMessage || "Search failed.");
      } finally {
        if (!controller.signal.aborted) setIsSearching(false);
      }
    };

    runSearch();
    return () => controller.abort();
  }, [debouncedQuery, activeStatus, fetchChats]);

  const createChat = useCallback(async (categoryId = null) => {
    try {
      const data = await chatApi.create(categoryId);
      setChats((prev) => [data.chat, ...prev]);
      return data.chat;
    } catch (err) {
      setError(err.userMessage || "Failed to create chat.");
      return null;
    }
  }, []);

  const renameChat = useCallback(async (chatId, newTitle) => {
    const previousChats = chats;
    setChats((prev) =>
      prev.map((c) =>
        c._id === chatId
          ? { ...c, title: newTitle, isTitleAutoGenerated: false }
          : c
      )
    );
    try {
      await chatApi.rename(chatId, newTitle);
    } catch (err) {
      setChats(previousChats);
      setError(err.userMessage || "Failed to rename chat.");
    }
  }, [chats]);

  const deleteChat = useCallback(async (chatId) => {
    const previousChats = chats;
    setChats((prev) => prev.filter((c) => c._id !== chatId));
    try {
      await chatApi.delete(chatId);
    } catch (err) {
      setChats(previousChats);
      setError(err.userMessage || "Failed to delete chat.");
    }
  }, [chats]);

  const archiveChat = useCallback(async (chatId, archive = true) => {
    const previousChats = chats;
    setChats((prev) => prev.filter((c) => c._id !== chatId));
    try {
      await chatApi.archive(chatId, archive);
    } catch (err) {
      setChats(previousChats);
      setError(err.userMessage || "Failed to archive chat.");
    }
  }, [chats]);

  const loadPage = useCallback((page) => {
    fetchChats(page, activeStatus);
  }, [fetchChats, activeStatus]);

  const updateChatPreview = useCallback((chatId, content) => {
    setChats((prev) =>
      prev.map((c) =>
        c._id === chatId
          ? { ...c, lastMessagePreview: content.slice(0, 180), lastMessageAt: new Date().toISOString() }
          : c
      )
    );
  }, []);

  return {
    chats,
    isLoading,
    isSearching,
    searchQuery,
    error,
    pagination,
    activeStatus,
    setSearchQuery,
    setActiveStatus,
    createChat,
    renameChat,
    deleteChat,
    archiveChat,
    loadPage,
    updateChatPreview,
    refresh: () => fetchChats(1, activeStatus),
  };
};

export default useChatHistory;
