import Chat from "../models/Chat.js";
import Message from "../models/Message.js";
import User from "../models/User.js";
import { getStructuredCompletion } from "./mistralClient.js";

// ─── Custom Error ─────────────────────────────────────────────────────────────

export class ChatHistoryError extends Error {
  constructor(message, code, isRetryable = false) {
    super(message);
    this.name = "ChatHistoryError";
    this.code = code;
    this.isRetryable = isRetryable;
  }
}

const PREVIEW_LENGTH = 180;

// ─── Create a New Chat ──────────────────────────────────────────────────────────
// The entry point a new conversation always starts from — called by the
// chat controller before the first message is ever sent, so a chatId
// exists for consultationOrchestrator.js's ConsultationSession (which
// requires a chatId up front) and for the frontend's URL routing.

export const createChat = async (userId, options = {}) => {
  const { categoryId = null } = options;

  const chat = await Chat.create({
    userId,
    categoryId,
    title: "New conversation",
    isTitleAutoGenerated: true,
  });

  await User.findByIdAndUpdate(userId, { $inc: { "usageStats.totalChats": 1 } });

  return chat;
};

// ─── Save a Message and Update the Parent Chat ─────────────────────────────────
// The single write path for persisting a turn. Called by the chat
// controller after ragChatService.generateRagResponse or
// consultationOrchestrator.processConsultationTurn produces a result —
// this function does not generate any content itself, it only persists
// what was already generated, keeping the write-path separate from the
// AI-generation logic in every other module.

export const saveMessage = async (chatId, userId, messageData) => {
  const {
    role,
    content,
    contentType = "text",
    citations = [],
    documentRefs = [],
    consultationPhase = null,
    tokenUsage = { inputTokens: 0, outputTokens: 0 },
    isStreamed = false,
  } = messageData;

  const chat = await Chat.findOne({ _id: chatId, userId, status: { $ne: "deleted" } });

  if (!chat) {
    throw new ChatHistoryError("Chat not found.", "CHAT_NOT_FOUND", false);
  }

  const message = await Message.create({
    chatId,
    role,
    content,
    contentType,
    citations,
    documentRefs,
    consultationPhase,
    tokenUsage,
    isStreamed,
  });

  // Update denormalised fields on the parent Chat in the same logical
  // operation — these two writes (Message create + Chat update) are not
  // wrapped in a transaction deliberately: a brief window where the
  // message exists but the chat's counters haven't caught up yet is an
  // acceptable, self-healing inconsistency (the next message write
  // corrects lastMessageAt regardless), and the operational cost of a
  // multi-document transaction for every single chat message is not
  // justified by this low a stakes inconsistency window.
  chat.messageCount += 1;
  chat.lastMessageAt = message.createdAt;
  chat.lastMessagePreview = content.slice(0, PREVIEW_LENGTH);

  // Auto-title generation: only on the first USER message, and only if
  // the user hasn't manually renamed the chat already (see isTitleAutoGenerated
  // on the Chat model for why this check is necessary).
  if (role === "user" && chat.messageCount <= 1 && chat.isTitleAutoGenerated) {
    chat.title = await generateAutoTitle(content);
  }

  await chat.save();

  if (role === "assistant") {
    await User.findByIdAndUpdate(userId, {
      $inc: { "usageStats.totalMessages": 1, "usageStats.monthlyTokensUsed": tokenUsage.outputTokens },
    });
  }

  return message;
};

// ─── Generate an Auto-Title from the First Message ─────────────────────────────
// A short, fast, cheap Claude call — deliberately tiny output schema since
// this runs on literally every new chat's first message.

const generateAutoTitle = async (firstUserMessage) => {
  const schema = {
    type: "object",
    properties: {
      title: {
        type: "string",
        description:
          "A short, specific chat title (max 6 words) summarising the user's legal situation, " +
          "e.g. 'Security Deposit Dispute' or 'Employment Termination Query'. No quotes, no punctuation at the end.",
      },
    },
    required: ["title"],
    additionalProperties: false,
  };

  try {
    const result = await getStructuredCompletion({
      systemPrompt:
        "Generate a short, specific title for a legal chat based on the user's opening message. Maximum 6 words.",
      userPrompt: firstUserMessage.slice(0, 500), // first message is plenty of signal; cap for cost
      jsonSchema: schema,
      maxTokens: 64,
    });

    return result.data.title.slice(0, 150);
  } catch (error) {
    // Title generation failing should never block a message from saving —
    // fall back to a truncated version of the message itself, which is
    // still more useful than the generic "New conversation" default.
    console.warn(`Auto-title generation failed, using fallback: ${error.message}`);
    return firstUserMessage.length > 60 ? `${firstUserMessage.slice(0, 57)}...` : firstUserMessage;
  }
};

// ─── Load a Chat with its Messages ─────────────────────────────────────────────
// "Load previous chats" — fetches the chat metadata and its full message
// thread in chronological order. Ownership is enforced at the query level
// (userId in the filter), following the same pattern as documentController.js
// from the Upload module.

export const loadChat = async (chatId, userId) => {
  const chat = await Chat.findOne({ _id: chatId, userId, status: { $ne: "deleted" } });

  if (!chat) {
    throw new ChatHistoryError("Chat not found.", "CHAT_NOT_FOUND", false);
  }

  const messages = await Message.find({ chatId }).sort({ createdAt: 1 });

  return { chat, messages };
};

// ─── List Chats (History List) ─────────────────────────────────────────────────
// Paginated, sorted by most recent activity. Uses only the denormalised
// fields on Chat (lastMessageAt, lastMessagePreview, messageCount) — never
// touches the Messages collection, which is what keeps this fast
// regardless of how long individual conversations have grown.

export const listChats = async (userId, options = {}) => {
  const { page = 1, limit = 20, categoryId = null, status = "active" } = options;

  const filter = { userId, status };
  if (categoryId) filter.categoryId = categoryId;

  const [chats, total] = await Promise.all([
    Chat.find(filter)
      .sort({ lastMessageAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit),
    Chat.countDocuments(filter),
  ]);

  return {
    chats,
    pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
  };
};

// ─── Search Chats ───────────────────────────────────────────────────────────────
// Uses MongoDB's native text search against the title + lastMessagePreview
// text index defined on the Chat model. This is intentionally a search
// over chat-level metadata, not full message content — searching every
// message body would require either a much heavier text index on the
// high-volume Messages collection or a dedicated search service, neither
// of which is justified for what is fundamentally a personal history list,
// not a web-scale search problem. A title/preview search covers the
// overwhelming majority of "find that chat about X" use cases.

export const searchChats = async (userId, query, options = {}) => {
  const { limit = 20 } = options;

  if (!query || query.trim().length === 0) {
    throw new ChatHistoryError("Search query cannot be empty.", "EMPTY_QUERY", false);
  }

  const chats = await Chat.find(
    {
      userId,
      status: { $ne: "deleted" },
      $text: { $search: query.trim() },
    },
    { score: { $meta: "textScore" } }
  )
    .sort({ score: { $meta: "textScore" } })
    .limit(limit);

  return chats;
};

// ─── Rename a Chat ───────────────────────────────────────────────────────────────
// Marks the title as manually set — this is the write that flips
// isTitleAutoGenerated to false, permanently protecting this title from
// the auto-title generator on any future message in this chat.

export const renameChat = async (chatId, userId, newTitle) => {
  const trimmedTitle = newTitle?.trim();

  if (!trimmedTitle || trimmedTitle.length === 0) {
    throw new ChatHistoryError("Title cannot be empty.", "EMPTY_TITLE", false);
  }

  if (trimmedTitle.length > 150) {
    throw new ChatHistoryError("Title is too long (max 150 characters).", "TITLE_TOO_LONG", false);
  }

  const chat = await Chat.findOneAndUpdate(
    { _id: chatId, userId, status: { $ne: "deleted" } },
    { $set: { title: trimmedTitle, isTitleAutoGenerated: false } },
    { new: true }
  );

  if (!chat) {
    throw new ChatHistoryError("Chat not found.", "CHAT_NOT_FOUND", false);
  }

  return chat;
};

// ─── Delete a Chat (Soft Delete) ─────────────────────────────────────────────────
// Mirrors the soft-delete pattern from documentController.js — the chat
// and its messages are hidden from all listing/loading queries immediately,
// but not purged, preserving the option for a future "undo" affordance and
// any audit requirements. A scheduled cleanup job (not part of this
// module) would handle permanent purging after a grace period, exactly as
// noted for documents in the Upload module.

export const deleteChat = async (chatId, userId) => {
  const chat = await Chat.findOneAndUpdate(
    { _id: chatId, userId, status: { $ne: "deleted" } },
    { $set: { status: "deleted", deletedAt: new Date() } },
    { new: true }
  );

  if (!chat) {
    throw new ChatHistoryError("Chat not found.", "CHAT_NOT_FOUND", false);
  }

  return chat;
};

// ─── Archive a Chat ───────────────────────────────────────────────────────────────
// A lighter-weight alternative to deletion — hides a chat from the default
// "active" list view without the soft-delete semantics (no deletedAt,
// fully reversible with zero ambiguity). Not explicitly requested, but a
// natural complement to delete/rename that the Chat model's status enum
// already supports, included here since it costs nothing extra to wire up.

export const archiveChat = async (chatId, userId, archived = true) => {
  const chat = await Chat.findOneAndUpdate(
    { _id: chatId, userId, status: { $ne: "deleted" } },
    { $set: { status: archived ? "archived" : "active" } },
    { new: true }
  );

  if (!chat) {
    throw new ChatHistoryError("Chat not found.", "CHAT_NOT_FOUND", false);
  }

  return chat;
};
