import mongoose from "mongoose";

// ─── Chat Schema ──────────────────────────────────────────────────────────────
// Represents one conversation session. Matches the Chats collection design
// from the original MongoDB schema: scoped to a user and a legal category,
// with denormalised counters (messageCount, lastMessageAt) so the history
// list can render without a separate aggregation query against Messages
// on every page load — that denormalisation is what keeps "list my chats"
// a single, fast, indexed query even with thousands of messages overall.

const chatSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    categoryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LegalCategory",
      default: null,
      // null until the consultation's issue-classification phase resolves
      // a category (see ConsultationSession.categorySlug) — kept loosely
      // coupled rather than required, since a chat can exist before
      // classification completes
    },

    title: {
      type: String,
      trim: true,
      maxlength: 150,
      default: "New conversation",
      // Auto-generated from the first user message once available;
      // user-editable thereafter via the rename endpoint
    },

    isTitleAutoGenerated: {
      type: Boolean,
      default: true,
      // Once a user manually renames a chat, this flips to false, and
      // the auto-title generator (chatHistoryService.js) must never
      // overwrite a title the user deliberately chose
    },

    status: {
      type: String,
      enum: ["active", "archived", "deleted"],
      default: "active",
      index: true,
    },

    summary: {
      text: { type: String, default: null },
      generatedAt: { type: Date, default: null },
      // Rolling LLM-generated summary for long threads — referenced by
      // ragChatService.js's MAX_HISTORY_TURNS comment as the mechanism
      // for context beyond the recent-turns window. Not populated by
      // this module; a separate summarisation job owns writing this.
    },

    documentIds: {
      type: [mongoose.Schema.Types.ObjectId],
      ref: "Document",
      default: [],
      // Documents in scope for this chat's RAG retrieval — drives the
      // documentIds option passed to retrievalService.retrieveContext
    },

    messageCount: {
      type: Number,
      default: 0,
      // Denormalised — incremented atomically alongside every message
      // insert in chatHistoryService.js, never recomputed via a count()
    },

    lastMessageAt: {
      type: Date,
      default: Date.now,
      index: true,
      // Denormalised — the primary sort key for "recent chats first"
    },

    lastMessagePreview: {
      type: String,
      default: "",
      maxlength: 200,
      // First ~200 chars of the most recent message — lets the history
      // list render a preview snippet without fetching the Messages
      // collection at all
    },

    deletedAt: {
      type: Date,
      default: null,
      // Soft-delete timestamp — mirrors the Document model's pattern
      // from the Upload module for the same reason: an undo window and
      // referential integrity if anything still points at this chat
    },
  },
  {
    timestamps: true,
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

// Primary history-list query: "my active chats, most recent first"
chatSchema.index({ userId: 1, status: 1, lastMessageAt: -1 });

// Text index for search — see chatHistoryService.js's searchChats function.
// Indexing both title and the message preview means a search for a word
// that appeared in the conversation (not just the title) still surfaces
// the chat, without needing to search the full Messages collection.
chatSchema.index({ title: "text", lastMessagePreview: "text" });

chatSchema.index({ categoryId: 1 });

// ─── Transform ────────────────────────────────────────────────────────────────

chatSchema.set("toJSON", {
  transform: (doc, ret) => {
    delete ret.__v;
    return ret;
  },
});

const Chat = mongoose.model("Chat", chatSchema);

export default Chat;
